@startuml

class URIBuilder{
  + setScheme(String) : URIBuilder
  + setHost(String) : URIBuilder
  + setPath(String) : URIBuilder
  + build() : URI
}

class URI {
  + toURL() : URL
}

class URL {
  + openConnection() : HttpURLConnection
}

class HttpURLConnection {
  + setRequestMethod(String) : void
  + getInputStream() : InputStream
}

class InputStream{
}

URIBuilder --o URI
URI --> URL
URL --> HttpURLConnection
HttpURLConnection --> InputStream

@enduml